I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 119, in script
    call screen corredor
ScriptError: could not find label 'sala3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\vitor\Downloads\renpy-8.3.2-sdk\renpy-8.3.2-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\vitor\Downloads\renpy-8.3.2-sdk\renpy-8.3.2-sdk\renpy\main.py", line 652, in main
    run(restart)
  File "C:\Users\vitor\Downloads\renpy-8.3.2-sdk\renpy-8.3.2-sdk\renpy\main.py", line 148, in run
    renpy.execution.run_context(True)
  File "C:\Users\vitor\Downloads\renpy-8.3.2-sdk\renpy-8.3.2-sdk\renpy\execution.py", line 958, in run_context
    context.run()
  File "game/script.rpy", line 119, in script
    call screen corredor
  File "C:\Users\vitor\Downloads\renpy-8.3.2-sdk\renpy-8.3.2-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'sala3'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.2.24090902
As cores da Saudade 1.0
Mon Nov 18 10:27:00 2024
